const SEED_DATA = {
  products: [
    { id: "p001", name: "Fresh Milk", category: "Dairy & Eggs", price: 32, unit: "500ml", image: "", description: "Fresh farm milk, pasteurized and pure.", stock: 50, badge: "Top Rated" },
    { id: "p002", name: "Amul Butter", category: "Dairy & Eggs", price: 56, unit: "100g", image: "", description: "Creamy and rich butter from Amul.", stock: 40, badge: "" },
    { id: "p003", name: "Full Cream Milk", category: "Dairy & Eggs", price: 68, unit: "1L", image: "", description: "Full cream milk for tea, coffee and cooking.", stock: 45, badge: "" },
    { id: "p004", name: "Paneer", category: "Dairy & Eggs", price: 80, unit: "200g", image: "", description: "Fresh cottage cheese, soft and rich in protein.", stock: 30, badge: "New" },
    { id: "p005", name: "Greek Yogurt", category: "Dairy & Eggs", price: 45, unit: "200g", image: "", description: "Thick and creamy Greek yogurt.", stock: 25, badge: "" },
    { id: "p006", name: "Banana", category: "Fresh Fruits", price: 40, unit: "1 dozen", image: "", description: "Ripe and sweet bananas, perfect for smoothies.", stock: 60, badge: "Top Rated" },
    { id: "p007", name: "Apple (Shimla)", category: "Fresh Fruits", price: 120, unit: "1kg", image: "", description: "Crisp Shimla apples, sweet and juicy.", stock: 35, badge: "" },
    { id: "p008", name: "Orange (Nagpur)", category: "Fresh Fruits", price: 80, unit: "1kg", image: "", description: "Juicy Nagpur oranges full of Vitamin C.", stock: 40, badge: "" },
    { id: "p009", name: "Mango (Alphonso)", category: "Fresh Fruits", price: 350, unit: "1kg", image: "", description: "King of fruits - Alphonso mangoes.", stock: 15, badge: "Premium" },
    { id: "p010", name: "Grapes (Green)", category: "Fresh Fruits", price: 90, unit: "500g", image: "", description: "Sweet green seedless grapes.", stock: 30, badge: "" },
    { id: "p011", name: "Strawberry", category: "Fresh Fruits", price: 60, unit: "250g", image: "", description: "Fresh red strawberries.", stock: 20, badge: "New" },
    { id: "p012", name: "Tomato", category: "Fresh Vegetables", price: 25, unit: "1kg", image: "", description: "Fresh ripe tomatoes for curries and salads.", stock: 80, badge: "Top Rated" },
    { id: "p013", name: "Potato", category: "Fresh Vegetables", price: 30, unit: "1kg", image: "", description: "Fresh potatoes for everyday cooking.", stock: 100, badge: "" },
    { id: "p014", name: "Onion", category: "Fresh Vegetables", price: 28, unit: "1kg", image: "", description: "Fresh red onions.", stock: 90, badge: "" },
    { id: "p015", name: "Spinach (Palak)", category: "Fresh Vegetables", price: 20, unit: "250g", image: "", description: "Fresh green spinach leaves.", stock: 50, badge: "" },
    { id: "p016", name: "Broccoli", category: "Fresh Vegetables", price: 55, unit: "250g", image: "", description: "Fresh green broccoli florets.", stock: 25, badge: "New" },
    { id: "p017", name: "Capsicum (Green)", category: "Fresh Vegetables", price: 35, unit: "250g", image: "", description: "Fresh green bell peppers.", stock: 35, badge: "" },
    { id: "p018", name: "Carrot", category: "Fresh Vegetables", price: 30, unit: "500g", image: "", description: "Fresh orange carrots.", stock: 45, badge: "" },
    { id: "p019", name: "Cucumber", category: "Fresh Vegetables", price: 20, unit: "500g", image: "", description: "Fresh crunchy cucumbers.", stock: 55, badge: "" },
    { id: "p020", name: "Lays Classic Salted", category: "Snacks & Namkeen", price: 20, unit: "52g", image: "", description: "Classic salted potato chips.", stock: 100, badge: "Top Rated" },
    { id: "p021", name: "Kurkure Masala Munch", category: "Snacks & Namkeen", price: 20, unit: "80g", image: "", description: "Crunchy masala flavored snack.", stock: 90, badge: "" },
    { id: "p022", name: "Haldiram Aloo Bhujia", category: "Snacks & Namkeen", price: 45, unit: "200g", image: "", description: "Crispy aloo bhujia namkeen.", stock: 60, badge: "" },
    { id: "p023", name: "Dark Fantasy", category: "Biscuits & Cookies", price: 35, unit: "75g", image: "", description: "Choco-filled biscuit cookies.", stock: 50, badge: "" },
    { id: "p024", name: "Oreo Biscuits", category: "Biscuits & Cookies", price: 30, unit: "120g", image: "", description: "Classic Oreo cream biscuits.", stock: 70, badge: "" },
    { id: "p025", name: "Coca-Cola", category: "Soft Drinks & Juices", price: 40, unit: "750ml", image: "", description: "Refreshing Coca-Cola.", stock: 80, badge: "Top Rated" },
    { id: "p026", name: "Fresh Juice (Mango)", category: "Soft Drinks & Juices", price: 60, unit: "1L", image: "", description: "100% natural mango juice.", stock: 30, badge: "" },
    { id: "p027", name: "Bisleri Water", category: "Soft Drinks & Juices", price: 20, unit: "1L", image: "", description: "Purified mineral water.", stock: 200, badge: "" },
    { id: "p028", name: "Green Tea", category: "Tea & Coffee", price: 120, unit: "25 bags", image: "", description: "Refreshing green tea bags.", stock: 40, badge: "New" },
    { id: "p029", name: "Nescafe Classic", category: "Tea & Coffee", price: 175, unit: "100g", image: "", description: "Classic coffee powder for instant coffee.", stock: 35, badge: "" },
    { id: "p030", name: "Tata Sampann Turmeric", category: "Spices & Masalas", price: 55, unit: "100g", image: "", description: "Pure turmeric powder.", stock: 50, badge: "" },
    { id: "p031", name: "Basmati Rice", category: "Rice, Atta & Grains", price: 180, unit: "1kg", image: "", description: "Premium long grain basmati rice.", stock: 40, badge: "Top Rated" },
    { id: "p032", name: "Toor Dal", category: "Pulses & Lentils", price: 130, unit: "1kg", image: "", description: "Split pigeon peas for delicious dal.", stock: 55, badge: "" },
    { id: "p033", name: "Whole Wheat Atta", category: "Rice, Atta & Grains", price: 65, unit: "1kg", image: "", description: "Freshly milled whole wheat flour.", stock: 60, badge: "" },
    { id: "p034", name: "Besan (Gram Flour)", category: "Rice, Atta & Grains", price: 50, unit: "500g", image: "", description: "Fine gram flour for cooking.", stock: 40, badge: "" },
    { id: "p035", name: "Poha (Flattened Rice)", category: "Rice, Atta & Grains", price: 35, unit: "500g", image: "", description: "Thin flattened rice flakes.", stock: 45, badge: "" },
    { id: "p036", name: "Brown Bread", category: "Bakery & Bread", price: 40, unit: "400g", image: "", description: "Freshly baked brown bread loaf.", stock: 30, badge: "Top Rated" },
    { id: "p037", name: "Pav Bun", category: "Bakery & Bread", price: 25, unit: "pack of 6", image: "", description: "Soft dinner pav buns.", stock: 25, badge: "" },
    { id: "p038", name: "Croissant", category: "Bakery & Bread", price: 50, unit: "2 pcs", image: "", description: "Flaky butter croissants.", stock: 15, badge: "New" },
    { id: "p039", name: "Garlic Bread", category: "Bakery & Bread", price: 65, unit: "200g", image: "", description: "Frozen garlic bread slices.", stock: 20, badge: "" },
    { id: "p040", name: "Frozen Peas", category: "Frozen Foods", price: 55, unit: "500g", image: "", description: "IQF frozen green peas.", stock: 35, badge: "" },
    { id: "p041", name: "French Fries", category: "Frozen Foods", price: 99, unit: "400g", image: "", description: "Frozen crispy french fries.", stock: 30, badge: "" },
    { id: "p042", name: "Chicken Nuggets", category: "Frozen Foods", price: 185, unit: "250g", image: "", description: "Frozen breaded chicken nuggets.", stock: 20, badge: "" },
    { id: "p043", name: "Frozen Paratha", category: "Frozen Foods", price: 85, unit: "pack of 8", image: "", description: "Ready-to-cook frozen parathas.", stock: 25, badge: "" },
    { id: "p044", name: "Sunflower Oil", category: "Cooking Oil & Ghee", price: 140, unit: "1L", image: "", description: "Refined sunflower cooking oil.", stock: 50, badge: "" },
    { id: "p045", name: "Sugar", category: "Rice, Atta & Grains", price: 45, unit: "1kg", image: "", description: "Fine granulated sugar.", stock: 80, badge: "" },
    { id: "p046", name: "Salt (Tata)", category: "Spices & Masalas", price: 22, unit: "1kg", image: "", description: "Iodized salt from Tata.", stock: 100, badge: "" },
    { id: "p047", name: "Cheese Slice", category: "Dairy & Eggs", price: 99, unit: "200g", image: "", description: "Processed cheese slices.", stock: 25, badge: "" },
    { id: "p048", name: "Pineapple", category: "Fresh Fruits", price: 50, unit: "1 pc", image: "", description: "Fresh sweet pineapple.", stock: 20, badge: "" },
    { id: "p049", name: "Pomegranate", category: "Fresh Fruits", price: 100, unit: "500g", image: "", description: "Fresh pomegranate seeds.", stock: 20, badge: "" },
    { id: "p050", name: "Mushroom", category: "Fresh Vegetables", price: 45, unit: "200g", image: "", description: "Fresh button mushrooms.", stock: 20, badge: "New" },
    { id: "p051", name: "Corn (Sweet)", category: "Fresh Vegetables", price: 35, unit: "2 pcs", image: "", description: "Fresh sweet corn cobs.", stock: 25, badge: "" },
    { id: "p052", name: "Curd (Amul)", category: "Dairy & Eggs", price: 25, unit: "400g", image: "", description: "Fresh creamy curd.", stock: 40, badge: "" },
    { id: "p053", name: "Cheerios", category: "Instant & Ready-to-Eat", price: 199, unit: "200g", image: "", description: "Healthy oat cereal loops.", stock: 15, badge: "" },
    { id: "p054", name: "Red Bull", category: "Soft Drinks & Juices", price: 115, unit: "250ml", image: "", description: "Energy drink.", stock: 30, badge: "" },
    { id: "p055", name: "Coconut Water", category: "Soft Drinks & Juices", price: 30, unit: "200ml", image: "", description: "Natural tender coconut water.", stock: 35, badge: "New" },
    { id: "p056", name: "Maggi Noodles", category: "Instant & Ready-to-Eat", price: 14, unit: "70g", image: "", description: "2-minute masala noodles.", stock: 120, badge: "Top Rated" },
    { id: "p057", name: "Maggi Pasta", category: "Instant & Ready-to-Eat", price: 45, unit: "300g", image: "", description: "Tasty pasta with sauce.", stock: 40, badge: "" },
    { id: "p058", name: "Chocos", category: "Biscuits & Cookies", price: 165, unit: "300g", image: "", description: "Chocolatey cereal for kids.", stock: 30, badge: "" },
    { id: "p059", name: "KitKat", category: "Chocolates & Candy", price: 20, unit: "40g", image: "", description: "Crispy wafer chocolate bar.", stock: 80, badge: "Top Rated" },
    { id: "p060", name: "Dairy Milk", category: "Chocolates & Candy", price: 80, unit: "150g", image: "", description: "Silky smooth milk chocolate.", stock: 70, badge: "" },
    { id: "p061", name: "Gems", category: "Chocolates & Candy", price: 30, unit: "44g", image: "", description: "Colorful chocolate button candies.", stock: 60, badge: "" },
    { id: "p062", name: "Green Label Tea", category: "Tea & Coffee", price: 210, unit: "500g", image: "", description: "Premium CTC green label tea.", stock: 45, badge: "" },
    { id: "p063", name: "Bru Instant Coffee", category: "Tea & Coffee", price: 165, unit: "100g", image: "", description: "Smooth instant coffee.", stock: 35, badge: "" },
    { id: "p064", name: "Masala Chai Mix", category: "Tea & Coffee", price: 85, unit: "200g", image: "", description: "Ready-to-use masala chai premix.", stock: 25, badge: "New" },
    { id: "p065", name: "Chicken Breast", category: "Meat & Seafood", price: 260, unit: "500g", image: "", description: "Fresh boneless chicken breast.", stock: 15, badge: "" },
    { id: "p066", name: "Mutton Curry Cut", category: "Meat & Seafood", price: 550, unit: "500g", image: "", description: "Fresh mutton curry cut pieces.", stock: 10, badge: "Premium" },
    { id: "p067", name: "Prawns (Cleaned)", category: "Meat & Seafood", price: 380, unit: "250g", image: "", description: "Fresh cleaned and deveined prawns.", stock: 12, badge: "" },
    { id: "p068", name: "Almonds", category: "Dry Fruits & Nuts", price: 320, unit: "250g", image: "", description: "Premium quality roasted almonds.", stock: 30, badge: "Top Rated" },
    { id: "p069", name: "Cashews", category: "Dry Fruits & Nuts", price: 380, unit: "250g", image: "", description: "Whole cashew nuts.", stock: 25, badge: "" },
    { id: "p070", name: "Walnuts", category: "Dry Fruits & Nuts", price: 450, unit: "250g", image: "", description: "Premium walnut kernels.", stock: 15, badge: "" },
    { id: "p071", name: "Honey", category: "Organic Products", price: 180, unit: "500g", image: "", description: "Pure natural honey.", stock: 30, badge: "Top Rated" },
    { id: "p072", name: "Organic Quinoa", category: "Organic Products", price: 299, unit: "500g", image: "", description: "Certified organic white quinoa.", stock: 20, badge: "" },
    { id: "p073", name: "Muesli", category: "Health & Wellness", price: 225, unit: "500g", image: "", description: "Healthy mixed fruit muesli.", stock: 25, badge: "" },
    { id: "p074", name: "Whey Protein", category: "Health & Wellness", price: 1499, unit: "1kg", image: "", description: "Chocolate flavored whey protein.", stock: 10, badge: "Premium" },
    { id: "p075", name: "Multivitamin Gummies", category: "Health & Wellness", price: 350, unit: "60 pcs", image: "", description: "Daily multivitamin gummies for adults.", stock: 20, badge: "New" },
    { id: "p076", name: "Head & Shoulders", category: "Personal Care", price: 210, unit: "400ml", image: "", description: "Anti-dandruff shampoo.", stock: 35, badge: "" },
    { id: "p077", name: "Colgate MaxFresh", category: "Personal Care", price: 95, unit: "150g", image: "", description: "Fresh mint toothpaste.", stock: 50, badge: "" },
    { id: "p078", name: "Dettol Soap", category: "Personal Care", price: 45, unit: "75g x 4", image: "", description: "Antibacterial bathing soap.", stock: 60, badge: "Top Rated" },
    { id: "p079", name: "Nestle Cerelac", category: "Baby Care", price: 185, unit: "300g", image: "", description: "Baby cereal with milk and wheat.", stock: 25, badge: "Top Rated" },
    { id: "p080", name: "Baby Diapers (MamyPoko)", category: "Baby Care", price: 399, unit: " pack of 30", image: "", description: "Extra absorb diapers medium size.", stock: 20, badge: "" },
    { id: "p081", name: "Baby Soap (Himalaya)", category: "Baby Care", price: 75, unit: "100g x 3", image: "", description: "Gentle baby bathing soap.", stock: 30, badge: "" },
    { id: "p082", name: "Surf Excel", category: "Cleaning Supplies", price: 135, unit: "500g", image: "", description: "Stain removal detergent powder.", stock: 45, badge: "Top Rated" },
    { id: "p083", name: "Vim Dishwash Liquid", category: "Cleaning Supplies", price: 99, unit: "500ml", image: "", description: "Lemon dishwash liquid gel.", stock: 40, badge: "" },
    { id: "p084", name: "Harpic Power Plus", category: "Household Essentials", price: 89, unit: "500ml", image: "", description: "Toilet cleaner liquid.", stock: 35, badge: "" },
    { id: "p085", name: "Lizol Floor Cleaner", category: "Household Essentials", price: 155, unit: "500ml", image: "", description: "Citrus disinfectant floor cleaner.", stock: 30, badge: "" },
    { id: "p086", name: "Whiskas Cat Food", category: "Pet Care", price: 320, unit: "480g", image: "", description: "Dry cat food with fish flavor.", stock: 15, badge: "" },
    { id: "p087", name: "Pedigree Dog Food", category: "Pet Care", price: 280, unit: "1kg", image: "", description: "Complete dog food chicken and vegetables.", stock: 20, badge: "Top Rated" },
    { id: "p088", name: "Parle-G", category: "Biscuits & Cookies", price: 10, unit: "80g", image: "", description: "Classic glucose biscuits.", stock: 150, badge: "" },
    { id: "p089", name: "Hide & Seek", category: "Biscuits & Cookies", price: 30, unit: "100g", image: "", description: "Chocolate chip cookies.", stock: 60, badge: "" },
    { id: "p090", name: "Ghee (Amul)", category: "Cooking Oil & Ghee", price: 275, unit: "500ml", image: "", description: "Pure cow ghee.", stock: 30, badge: "Top Rated" },
    { id: "p091", name: "Mustard Oil", category: "Cooking Oil & Ghee", price: 120, unit: "1L", image: "", description: "Cold-pressed mustard oil.", stock: 25, badge: "" },
    { id: "p092", name: "Chana Dal", category: "Pulses & Lentils", price: 90, unit: "1kg", image: "", description: "Split Bengal gram lentils.", stock: 50, badge: "" },
    { id: "p093", name: "Moong Dal", category: "Pulses & Lentils", price: 110, unit: "1kg", image: "", description: "Split green gram lentils.", stock: 45, badge: "" },
    { id: "p094", name: "Masoor Dal", category: "Pulses & Lentils", price: 95, unit: "1kg", image: "", description: "Split red lentils.", stock: 40, badge: "" },
    { id: "p095", name: "Biryani Masala", category: "Spices & Masalas", price: 65, unit: "50g", image: "", description: "Aromatic biryani spice blend.", stock: 30, badge: "" },
    { id: "p096", name: "Garam Masala", category: "Spices & Masalas", price: 55, unit: "50g", image: "", description: "Traditional garam masala powder.", stock: 35, badge: "" },
    { id: "p097", name: "Paneer Tikka Masala", category: "Instant & Ready-to-Eat", price: 75, unit: "100g", image: "", description: "Ready-to-cook paneer tikka masala paste.", stock: 25, badge: "New" },
    { id: "p098", name: "Frozen Momos", category: "Frozen Foods", price: 120, unit: "pack of 12", image: "", description: "Steamed chicken momos, frozen.", stock: 20, badge: "" },
    { id: "p099", name: "Britannia Rusk", category: "Bakery & Bread", price: 35, unit: "200g", image: "", description: "Toasted tea rusk biscuits.", stock: 40, badge: "" },
    { id: "p100", name: "Coconut Oil", category: "Personal Care", price: 135, unit: "500ml", image: "", description: "Pure coconut hair oil.", stock: 35, badge: "" },
    { id: "p101", name: "Amul Ice Cream", category: "Frozen Foods", price: 80, unit: "500ml", image: "", description: "Vanilla flavored ice cream.", stock: 25, badge: "" },
    { id: "p102", name: "Saffola Gold Oil", category: "Cooking Oil & Ghee", price: 199, unit: "1L", image: "", description: "Healthy cooking oil blend.", stock: 30, badge: "Top Rated" },
    { id: "p103", name: "Act II Popcorn", category: "Snacks & Namkeen", price: 40, unit: "70g", image: "", description: "Butter-flavored microwave popcorn.", stock: 45, badge: "" },
    { id: "p104", name: "Bournvita", category: "Health & Wellness", price: 225, unit: "500g", image: "", description: "Chocolate health drink for kids.", stock: 35, badge: "Top Rated" },
    { id: "p105", name: "PediaSure", category: "Health & Wellness", price: 399, unit: "400g", image: "", description: "Nutritional supplement for kids growth.", stock: 20, badge: "" },
    { id: "p106", name: "Tropicana Juice", category: "Soft Drinks & Juices", price: 65, unit: "1L", image: "", description: "100% orange juice, no added sugar.", stock: 40, badge: "" },
    { id: "p107", name: "Frooti Mango Drink", category: "Soft Drinks & Juices", price: 10, unit: "200ml", image: "", description: "Tasty mango-flavored drink.", stock: 100, badge: "" },
    { id: "p108", name: "Thums Up", category: "Soft Drinks & Juices", price: 40, unit: "750ml", image: "", description: "Strong carbonated soft drink.", stock: 70, badge: "" },
    { id: "p109", name: "Real Fruit Juice", category: "Soft Drinks & Juices", price: 55, unit: "1L", image: "", description: "Mixed fruit juice.", stock: 35, badge: "" },
    { id: "p110", name: "Paper Boat Aamras", category: "Soft Drinks & Juices", price: 30, unit: "200ml", image: "", description: "Traditional aamras mango drink.", stock: 30, badge: "New" },
    { id: "p111", name: "Amul Lassi", category: "Dairy & Eggs", price: 25, unit: "200ml", image: "", description: "Sweet lassi drink.", stock: 40, badge: "" },
    { id: "p112", name: "Amul Kool", category: "Dairy & Eggs", price: 20, unit: "200ml", image: "", description: "Flavored milk drink - coffee.", stock: 50, badge: "" },
    { id: "p113", name: "Mother Dairy Milk", category: "Dairy & Eggs", price: 30, unit: "500ml", image: "", description: "Toned milk from Mother Dairy.", stock: 60, badge: "" },
    { id: "p114", name: "Eggs (Brown)", category: "Dairy & Eggs", price: 90, unit: "6 pcs", image: "", description: "Farm-fresh brown eggs.", stock: 45, badge: "" },
    { id: "p115", name: "Britannia Cheese", category: "Dairy & Eggs", price: 110, unit: "200g", image: "", description: "Processed cheese block.", stock: 25, badge: "" },
    { id: "p116", name: "Idli Rice", category: "Rice, Atta & Grains", price: 75, unit: "1kg", image: "", description: "Par-boiled rice for idli and dosa.", stock: 30, badge: "" },
    { id: "p117", name: "Ragi Flour", category: "Rice, Atta & Grains", price: 55, unit: "500g", image: "", description: "Finger millet flour for healthy cooking.", stock: 25, badge: "New" },
    { id: "p118", name: "Maida (Refined Flour)", category: "Rice, Atta & Grains", price: 40, unit: "1kg", image: "", description: "Fine refined wheat flour.", stock: 50, badge: "" },
    { id: "p119", name: "Sooji (Semolina)", category: "Rice, Atta & Grains", price: 45, unit: "500g", image: "", description: "Fine semolina for upma and halwa.", stock: 35, badge: "" },
    { id: "p120", name: "Jowar Flour", category: "Rice, Atta & Grains", price: 60, unit: "500g", image: "", description: "Sorghum flour for rotis.", stock: 20, badge: "" },
    { id: "p121", name: "Urad Dal", category: "Pulses & Lentils", price: 120, unit: "1kg", image: "", description: "Split black gram lentils.", stock: 40, badge: "" },
    { id: "p122", name: "Rajma (Kidney Beans)", category: "Pulses & Lentils", price: 100, unit: "500g", image: "", description: "Red kidney beans.", stock: 35, badge: "" },
    { id: "p123", name: "Kabuli Chana", category: "Pulses & Lentils", price: 110, unit: "500g", image: "", description: "White chickpeas for chana masala.", stock: 30, badge: "" },
    { id: "p124", name: "Black Chana", category: "Pulses & Lentils", price: 85, unit: "500g", image: "", description: "Black chickpeas.", stock: 25, badge: "" },
    { id: "p125", name: "Chilli Powder", category: "Spices & Masalas", price: 45, unit: "100g", image: "", description: "Kashmiri red chilli powder.", stock: 50, badge: "" },
    { id: "p126", name: "Coriander Powder", category: "Spices & Masalas", price: 40, unit: "100g", image: "", description: "Freshly ground coriander powder.", stock: 45, badge: "" },
    { id: "p127", name: "Cumin Seeds", category: "Spices & Masalas", price: 55, unit: "100g", image: "", description: "Whole cumin seeds for tempering.", stock: 40, badge: "" },
    { id: "p128", name: "Kitchen King Masala", category: "Spices & Masalas", price: 70, unit: "100g", image: "", description: "Multi-purpose kitchen masala.", stock: 30, badge: "" },
    { id: "p129", name: "Chat Masala", category: "Spices & Masalas", price: 50, unit: "50g", image: "", description: "Tangy chat masala for snacks.", stock: 35, badge: "" },
    { id: "p130", name: "Pav Bhaji Masala", category: "Spices & Masalas", price: 60, unit: "50g", image: "", description: "Special pav bhaji spice blend.", stock: 25, badge: "" },
    { id: "p131", name: "Maggie Pasta", category: "Instant & Ready-to-Eat", price: 55, unit: "350g", image: "", description: "Cheesy pasta in 2 minutes.", stock: 30, badge: "" },
    { id: "p132", name: "Knorr Soup", category: "Instant & Ready-to-Eat", price: 35, unit: "44g", image: "", description: "Sweet corn veg soup mix.", stock: 40, badge: "" },
    { id: "p133", name: "Yippee Noodles", category: "Instant & Ready-to-Eat", price: 14, unit: "60g", image: "", description: "Magic masala instant noodles.", stock: 80, badge: "" },
    { id: "p134", name: "Haldiram Aloo Tikki", category: "Frozen Foods", price: 110, unit: "pack of 4", image: "", description: "Frozen aloo tikki patties.", stock: 20, badge: "" },
    { id: "p135", name: "Samosa (Frozen)", category: "Frozen Foods", price: 150, unit: "pack of 6", image: "", description: "Ready-to-fry vegetable samosas.", stock: 15, badge: "" },
    { id: "p136", name: "Idli Dosa Batter", category: "Instant & Ready-to-Eat", price: 50, unit: "500g", image: "", description: "Ready-to-use fermented batter.", stock: 25, badge: "New" },
    { id: "p137", name: "Peanut Butter", category: "Health & Wellness", price: 199, unit: "400g", image: "", description: "Creamy peanut butter, no sugar.", stock: 20, badge: "" },
    { id: "p138", name: "Oats (Quaker)", category: "Health & Wellness", price: 145, unit: "1kg", image: "", description: "Rolled oats for healthy breakfast.", stock: 30, badge: "Top Rated" },
    { id: "p139", name: "Flax Seeds", category: "Health & Wellness", price: 120, unit: "200g", image: "", description: "Omega-3 rich flax seeds.", stock: 25, badge: "New" },
    { id: "p140", name: "Chia Seeds", category: "Health & Wellness", price: 180, unit: "200g", image: "", description: "Organic chia seeds.", stock: 20, badge: "" },
    { id: "p141", name: "Aloe Vera Gel", category: "Personal Care", price: 75, unit: "150ml", image: "", description: "Pure aloe vera gel for skin.", stock: 35, badge: "" },
    { id: "p142", name: "Vivel Soap", category: "Personal Care", price: 35, unit: "100g", image: "", description: "Soft almond oil bathing soap.", stock: 50, badge: "" },
    { id: "p143", name: "Vaseline Lotion", category: "Personal Care", price: 120, unit: "200ml", image: "", description: "Intensive care body lotion.", stock: 30, badge: "" },
    { id: "p144", name: "Nivea Lip Balm", category: "Personal Care", price: 99, unit: "4.8g", image: "", description: "Cherry lip balm for soft lips.", stock: 25, badge: "" },
    { id: "p145", name: "Himalaya Face Wash", category: "Personal Care", price: 110, unit: "100ml", image: "", description: "Neem face wash for clear skin.", stock: 30, badge: "Top Rated" },
    { id: "p146", name: "Baygon Spray", category: "Household Essentials", price: 145, unit: "600ml", image: "", description: "Insect killer spray.", stock: 20, badge: "" },
    { id: "p147", name: "Odomos Cream", category: "Household Essentials", price: 80, unit: "50ml", image: "", description: "Mosquito repellent cream.", stock: 35, badge: "" },
    { id: "p148", name: "Lizol Wipes", category: "Cleaning Supplies", price: 99, unit: "40 pcs", image: "", description: "Surface cleaning wipes.", stock: 25, badge: "New" },
    { id: "p149", name: "Colin Glass Cleaner", category: "Cleaning Supplies", price: 75, unit: "500ml", image: "", description: "Glass and surface cleaner.", stock: 30, badge: "" },
    { id: "p150", name: "Comfort Fabric Softener", category: "Cleaning Supplies", price: 95, unit: "860ml", image: "", description: "Liquid fabric conditioner.", stock: 25, badge: "" },
    { id: "p151", name: "Blue Band Spread", category: "Bakery & Bread", price: 50, unit: "200g", image: "", description: "Margarine spread for bread.", stock: 30, badge: "" },
    { id: "p152", name: "Wheat Rusks", category: "Bakery & Bread", price: 30, unit: "200g", image: "", description: "Crispy whole wheat rusks.", stock: 35, badge: "" },
    { id: "p153", name: "Multigrain Bread", category: "Bakery & Bread", price: 55, unit: "400g", image: "", description: "Healthy multigrain bread loaf.", stock: 20, badge: "" },
    { id: "p154", name: "Atta Biscuits", category: "Biscuits & Cookies", price: 15, unit: "100g", image: "", description: "Homestyle wheat biscuits.", stock: 60, badge: "" },
    { id: "p155", name: "Marie Gold", category: "Biscuits & Cookies", price: 25, unit: "250g", image: "", description: "Light and crispy Marie biscuits.", stock: 70, badge: "" },
    { id: "p156", name: "Good Day Biscuits", category: "Biscuits & Cookies", price: 30, unit: "100g", image: "", description: "Butter cookies with cashews.", stock: 50, badge: "" },
    { id: "p157", name: "Munch", category: "Chocolates & Candy", price: 10, unit: "22g", image: "", description: "Crunchy chocolate bar.", stock: 80, badge: "" },
    { id: "p158", name: "Perk", category: "Chocolates & Candy", price: 10, unit: "20g", image: "", description: "Wafer chocolate bar.", stock: 75, badge: "" },
    { id: "p159", name: "Eclairs", category: "Chocolates & Candy", price: 10, unit: "30g", image: "", description: "Chocolate-filled caramel candy.", stock: 90, badge: "" },
    { id: "p160", name: "Pulse Candy", category: "Chocolates & Candy", price: 10, unit: "28g", image: "", description: "Kachcha aam flavored hard candy.", stock: 100, badge: "" },
    { id: "p161", name: "Taj Mahal Tea", category: "Tea & Coffee", price: 250, unit: "500g", image: "", description: "Premium luxury tea.", stock: 25, badge: "" },
    { id: "p162", name: "Red Label Tea", category: "Tea & Coffee", price: 180, unit: "500g", image: "", description: "Everyday health tea.", stock: 40, badge: "Top Rated" },
    { id: "p163", name: "Sleepy Owl Coffee", category: "Tea & Coffee", price: 299, unit: "200g", image: "", description: "Premium ground coffee.", stock: 15, badge: "New" },
    { id: "p164", name: "Raw Mango Pickle", category: "Spices & Masalas", price: 85, unit: "200g", image: "", description: "Homestyle raw mango pickle.", stock: 30, badge: "" },
    { id: "p165", name: "Lemon Pickle", category: "Spices & Masalas", price: 75, unit: "200g", image: "", description: "Tangy lemon pickle.", stock: 25, badge: "" },
    { id: "p166", name: "Jam (Kissan)", category: "Bakery & Bread", price: 95, unit: "500g", image: "", description: "Mixed fruit jam.", stock: 35, badge: "" },
    { id: "p167", name: "Honey (Dabur)", category: "Organic Products", price: 150, unit: "500g", image: "", description: "Pure natural honey.", stock: 40, badge: "Top Rated" },
    { id: "p168", name: "Jaggery (Gur)", category: "Organic Products", price: 40, unit: "500g", image: "", description: "Traditional unrefined sugar.", stock: 30, badge: "" },
    { id: "p169", name: "Dry Dates", category: "Dry Fruits & Nuts", price: 200, unit: "250g", image: "", description: "Sweet dry dates (kharek).", stock: 20, badge: "" },
    { id: "p170", name: "Pistachios", category: "Dry Fruits & Nuts", price: 500, unit: "250g", image: "", description: "Premium roasted pistachios.", stock: 15, badge: "Premium" }
  ],
  banners: [
    { id: "b001", title: "Fresh Fruits", subtitle: "Get 20% off on all seasonal fruits", gradient: "linear-gradient(135deg, #2d6a4f, #40916c)", link: "shop.html?cat=Fresh Fruits", image: "", active: true, order: 1 },
    { id: "b002", title: "Daily Essentials", subtitle: "Free delivery on orders above ₹200", gradient: "linear-gradient(135deg, #f48c06, #f4a261)", link: "shop.html", image: "", active: true, order: 2 },
    { id: "b003", title: "New Arrivals", subtitle: "Try our newly added products", gradient: "linear-gradient(135deg, #40916c, #74c69d)", link: "shop.html", image: "", active: true, order: 3 }
  ],
  catalogs: [
    { id: "c001", name: "Fresh Fruits", emoji: "🍎", description: "Seasonal and exotic fruits", image: "", active: true, order: 1 },
    { id: "c002", name: "Fresh Vegetables", emoji: "🥦", description: "Farm fresh vegetables", image: "", active: true, order: 2 },
    { id: "c003", name: "Dairy & Eggs", emoji: "🥛", description: "Fresh milk, butter, paneer and eggs", image: "", active: true, order: 3 },
    { id: "c004", name: "Bakery & Bread", emoji: "🍞", description: "Fresh bread, buns and pastries", image: "", active: true, order: 4 },
    { id: "c005", name: "Rice, Atta & Grains", emoji: "🌾", description: "Rice, flour, sugar and essentials", image: "", active: true, order: 5 },
    { id: "c006", name: "Pulses & Lentils", emoji: "🫘", description: "Toor dal, moong dal and more", image: "", active: true, order: 6 },
    { id: "c007", name: "Cooking Oil & Ghee", emoji: "🫗", description: "Sunflower oil, mustard oil, ghee", image: "", active: true, order: 7 },
    { id: "c008", name: "Spices & Masalas", emoji: "🌶️", description: "Turmeric, garam masala, spices", image: "", active: true, order: 8 },
    { id: "c009", name: "Snacks & Namkeen", emoji: "🍿", description: "Chips, namkeen and savories", image: "", active: true, order: 9 },
    { id: "c010", name: "Biscuits & Cookies", emoji: "🍪", description: "Biscuits, cookies and rusks", image: "", active: true, order: 10 },
    { id: "c011", name: "Chocolates & Candy", emoji: "🍫", description: "Chocolate bars, candies and treats", image: "", active: true, order: 11 },
    { id: "c012", name: "Tea & Coffee", emoji: "☕", description: "Tea, coffee and chai essentials", image: "", active: true, order: 12 },
    { id: "c013", name: "Soft Drinks & Juices", emoji: "🥤", description: "Cold drinks, juices and water", image: "", active: true, order: 13 },
    { id: "c014", name: "Instant & Ready-to-Eat", emoji: "🍜", description: "Maggi, pasta, ready-to-cook items", image: "", active: true, order: 14 },
    { id: "c015", name: "Frozen Foods", emoji: "🧊", description: "Frozen snacks and ready-to-cook", image: "", active: true, order: 15 },
    { id: "c016", name: "Meat & Seafood", emoji: "🍗", description: "Chicken, mutton and seafood", image: "", active: true, order: 16 },
    { id: "c017", name: "Personal Care", emoji: "🧴", description: "Shampoo, soap, toothpaste", image: "", active: true, order: 17 },
    { id: "c018", name: "Baby Care", emoji: "👶", description: "Baby food, diapers and soap", image: "", active: true, order: 18 },
    { id: "c019", name: "Household Essentials", emoji: "🏠", description: "Toilet cleaner, floor cleaner", image: "", active: true, order: 19 },
    { id: "c020", name: "Cleaning Supplies", emoji: "🧹", description: "Detergent, dishwash and more", image: "", active: true, order: 20 },
    { id: "c021", name: "Pet Care", emoji: "🐾", description: "Dog food, cat food and accessories", image: "", active: true, order: 21 },
    { id: "c022", name: "Organic Products", emoji: "🌿", description: "Honey, quinoa and organic items", image: "", active: true, order: 22 },
    { id: "c023", name: "Dry Fruits & Nuts", emoji: "🥜", description: "Almonds, cashews, walnuts", image: "", active: true, order: 23 },
    { id: "c024", name: "Health & Wellness", emoji: "💊", description: "Supplements, muesli and health foods", image: "", active: true, order: 24 }
  ]
};
